services:
  postgresql:
    image: postgres:16-alpine
    expose:
      - 5432
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres-data:/var/lib/postgres/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgresql}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_DB=${POSTGRES_DB:-app}
  redis:
    image: redis:7-alpine
    expose:
      - 6379
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/var/lib/redis/data

volumes:
  postgres-data:
  redis-data:
